#!/usr/bin/env node

const mdImgFormat = require('./index').mdImgFormat

if (process.argv.length < 4) {
  console.log('Usage:')
  console.log('md-img-format <markdown file> <style>')
  console.log('example: md-img-format a.md width:200px')
}
const inputFile = process.argv[2]
const style = process.argv[3]

mdImgFormat(inputFile, style)